# Generated by Django 4.2.5 on 2023-11-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduce',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
